### ISSUE TITLE
Should tagging multiple users be considered spam?

### ISSUE THREAD

**Issue by DecimalTurn** [DecimalTurn/Comment-Filter#8]
This article details a spam campaign where comments would tag multiple accounts:
https://djanes.xyz/spam-on-github-is-getting-crazy-these-days/

Should this be considered spamming? How many accounts is too many in a single comment? More than 3?

**Comment by cristianbuse** [comment]
I never had the need to tag more than 2 accounts. I would say 3 is enough as a maximum allowed.

**Comment by cristianbuse** [comment]
Unrelated to the issue. The Full Changelog link you post on a new release, is that suppose to compare with the previous version? Because the [v0...v0.1.4](https://github.com/DecimalTurn/Comment-Filter/compare/v0...v0.1.4) doesn't show anything. If I understand correctly v0 defaults to v0.1.4 and then basically it compares v0.1.4 with v0.1.4

**Comment by DecimalTurn** [comment]
@cristianbuse good catch regarding the Changelog! I was using the automated release description generation, but it is indeed getting confused due to the presence of the tag `v0`. `v0` is just a tag I manually update to match the latest minor version of v0. Should be fixed now.
